/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountAddRequest
 */
export interface AccountAddRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountAddRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AccountAddRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AccountAddRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AccountAddRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AccountAddRequest
     */
    username: string;
}


