/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountUnlockRequest
 */
export interface AccountUnlockRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountUnlockRequest
     */
    hostName?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUnlockRequest
     */
    tenantName?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUnlockRequest
     */
    username: string;
}


