/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommissionResponse } from './commission-response';

/**
 * 
 * @export
 * @interface CalculationResponse
 */
export interface CalculationResponse {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof CalculationResponse
     */
    assignedVariables: { [key: string]: object; };
    /**
     * 
     * @type {Array<CommissionResponse>}
     * @memberof CalculationResponse
     */
    commissions: Array<CommissionResponse>;
    /**
     * 
     * @type {number}
     * @memberof CalculationResponse
     */
    premium: number;
    /**
     * 
     * @type {number}
     * @memberof CalculationResponse
     */
    technicalPremium?: number;
}


