/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldGroupCreateRequest } from './field-group-create-request';
import { FieldGroupUpdateRequest } from './field-group-update-request';
import { SubClaimCreateRequest } from './sub-claim-create-request';
import { SubClaimUpdateRequest } from './sub-claim-update-request';

/**
 * 
 * @export
 * @interface Claim3UpdateRequest
 */
export interface Claim3UpdateRequest {
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof Claim3UpdateRequest
     */
    addFieldGroups: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {Array<SubClaimCreateRequest>}
     * @memberof Claim3UpdateRequest
     */
    addSubClaims: Array<SubClaimCreateRequest>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Claim3UpdateRequest
     */
    fieldValues?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<string>}
     * @memberof Claim3UpdateRequest
     */
    removeFieldGroups: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Claim3UpdateRequest
     */
    status?: Claim3UpdateRequestStatusEnum;
    /**
     * 
     * @type {Array<FieldGroupUpdateRequest>}
     * @memberof Claim3UpdateRequest
     */
    updateFieldGroups: Array<FieldGroupUpdateRequest>;
    /**
     * 
     * @type {Array<SubClaimUpdateRequest>}
     * @memberof Claim3UpdateRequest
     */
    updateSubClaims: Array<SubClaimUpdateRequest>;
}

/**
    * @export
    * @enum {string}
    */
export enum Claim3UpdateRequestStatusEnum {
    Open = 'open',
    Closed = 'closed'
}



