/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Claim3Response } from './claim3-response';

/**
 * 
 * @export
 * @interface Claim3PageResponse
 */
export interface Claim3PageResponse {
    /**
     * 
     * @type {Array<Claim3Response>}
     * @memberof Claim3PageResponse
     */
    claims: Array<Claim3Response>;
    /**
     * 
     * @type {string}
     * @memberof Claim3PageResponse
     */
    pagingToken?: string;
}


