/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Media } from './media';
import { SubClaimResponse } from './sub-claim-response';

/**
 * 
 * @export
 * @interface Claim3Response
 */
export interface Claim3Response {
    /**
     * 
     * @type {string}
     * @memberof Claim3Response
     */
    currentStatus: Claim3ResponseCurrentStatusEnum;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: Array<string>; }; }}
     * @memberof Claim3Response
     */
    fieldGroupsByLocator: { [key: string]: { [key: string]: Array<string>; }; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Claim3Response
     */
    fieldValues: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof Claim3Response
     */
    locator: string;
    /**
     * 
     * @type {{ [key: string]: Media; }}
     * @memberof Claim3Response
     */
    mediaByLocator: { [key: string]: Media; };
    /**
     * 
     * @type {string}
     * @memberof Claim3Response
     */
    policyLocator: string;
    /**
     * 
     * @type {string}
     * @memberof Claim3Response
     */
    productName: string;
    /**
     * 
     * @type {Array<SubClaimResponse>}
     * @memberof Claim3Response
     */
    subClaims: Array<SubClaimResponse>;
}

/**
    * @export
    * @enum {string}
    */
export enum Claim3ResponseCurrentStatusEnum {
    Pending = 'pending',
    Open = 'open',
    Closed = 'closed'
}



