/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DateOffsetConfiguration
 */
export interface DateOffsetConfiguration {
    /**
     * 
     * @type {number}
     * @memberof DateOffsetConfiguration
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof DateOffsetConfiguration
     */
    field: DateOffsetConfigurationFieldEnum;
    /**
     * 
     * @type {boolean}
     * @memberof DateOffsetConfiguration
     */
    roundToDay?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum DateOffsetConfigurationFieldEnum {
    Year = 'year',
    Month = 'month',
    Day = 'day',
    Second = 'second'
}



