/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentRenderResponse
 */
export interface DocumentRenderResponse {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof DocumentRenderResponse
     */
    assignedVariables: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof DocumentRenderResponse
     */
    renderedHtmlUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRenderResponse
     */
    renderedPdfUrl?: string;
}


