/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PolicyDocumentConfiguration } from './policy-document-configuration';

/**
 * 
 * @export
 * @interface EndorsementConfigurationResponse
 */
export interface EndorsementConfigurationResponse {
    /**
     * 
     * @type {string}
     * @memberof EndorsementConfigurationResponse
     */
    displayName: string;
    /**
     * 
     * @type {Array<PolicyDocumentConfiguration>}
     * @memberof EndorsementConfigurationResponse
     */
    documents: Array<PolicyDocumentConfiguration>;
    /**
     * 
     * @type {string}
     * @memberof EndorsementConfigurationResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EndorsementConfigurationResponse
     */
    reprice: EndorsementConfigurationResponseRepriceEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum EndorsementConfigurationResponseRepriceEnum {
    Always = 'always',
    Never = 'never',
    Input = 'input',
    All = 'all'
}



