/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldGroupCreateRequest } from './field-group-create-request';
import { FieldGroupUpdateRequest } from './field-group-update-request';
import { PerilCreateRequest } from './peril-create-request';
import { PerilUpdateRequest } from './peril-update-request';

/**
 * 
 * @export
 * @interface EndorsementExposureUpdateRequest
 */
export interface EndorsementExposureUpdateRequest {
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof EndorsementExposureUpdateRequest
     */
    addFieldGroups: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {Array<PerilCreateRequest>}
     * @memberof EndorsementExposureUpdateRequest
     */
    addPerils: Array<PerilCreateRequest>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EndorsementExposureUpdateRequest
     */
    endPerils: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EndorsementExposureUpdateRequest
     */
    exposureLocator: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof EndorsementExposureUpdateRequest
     */
    fieldValues: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<string>}
     * @memberof EndorsementExposureUpdateRequest
     */
    removeFieldGroups: Array<string>;
    /**
     * 
     * @type {Array<FieldGroupUpdateRequest>}
     * @memberof EndorsementExposureUpdateRequest
     */
    updateFieldGroups: Array<FieldGroupUpdateRequest>;
    /**
     * 
     * @type {Array<PerilUpdateRequest>}
     * @memberof EndorsementExposureUpdateRequest
     */
    updatePerils: Array<PerilUpdateRequest>;
}


