/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EndorsementExposureUpdateRequest } from './endorsement-exposure-update-request';
import { ExposureCreateRequest } from './exposure-create-request';
import { FieldGroupCreateRequest } from './field-group-create-request';
import { FieldGroupUpdateRequest } from './field-group-update-request';

/**
 * 
 * @export
 * @interface EndorsementCreateRequest
 */
export interface EndorsementCreateRequest {
    /**
     * 
     * @type {Array<ExposureCreateRequest>}
     * @memberof EndorsementCreateRequest
     */
    addExposures?: Array<ExposureCreateRequest>;
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof EndorsementCreateRequest
     */
    addFieldGroups?: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EndorsementCreateRequest
     */
    endExposures?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EndorsementCreateRequest
     */
    endorsementName: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof EndorsementCreateRequest
     */
    fieldValues?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<string>}
     * @memberof EndorsementCreateRequest
     */
    removeFieldGroups?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EndorsementCreateRequest
     */
    reprice?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EndorsementCreateRequest
     */
    state?: EndorsementCreateRequestStateEnum;
    /**
     * 
     * @type {Array<EndorsementExposureUpdateRequest>}
     * @memberof EndorsementCreateRequest
     */
    updateExposures?: Array<EndorsementExposureUpdateRequest>;
    /**
     * 
     * @type {Array<FieldGroupUpdateRequest>}
     * @memberof EndorsementCreateRequest
     */
    updateFieldGroups?: Array<FieldGroupUpdateRequest>;
}

/**
    * @export
    * @enum {string}
    */
export enum EndorsementCreateRequestStateEnum {
    Application = 'application',
    Quoted = 'quoted',
    Accepted = 'accepted',
    Issued = 'issued'
}



