/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EndorsementUpdateRequest } from './endorsement-update-request';

/**
 * 
 * @export
 * @interface EndorsementActionRequest
 */
export interface EndorsementActionRequest {
    /**
     * 
     * @type {string}
     * @memberof EndorsementActionRequest
     */
    action?: EndorsementActionRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof EndorsementActionRequest
     */
    conflictHandling?: EndorsementActionRequestConflictHandlingEnum;
    /**
     * 
     * @type {EndorsementUpdateRequest}
     * @memberof EndorsementActionRequest
     */
    endorsementUpdate?: EndorsementUpdateRequest;
}

/**
    * @export
    * @enum {string}
    */
export enum EndorsementActionRequestActionEnum {
    Discard = 'discard',
    Quote = 'quote',
    Accept = 'accept',
    Issue = 'issue',
    Invalidate = 'invalidate',
    Update = 'update'
}
/**
    * @export
    * @enum {string}
    */
export enum EndorsementActionRequestConflictHandlingEnum {
    Block = 'block',
    Invalidate = 'invalidate'
}



