/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EntityResponse2
 */
export interface EntityResponse2 {
    /**
     * 
     * @type {string}
     * @memberof EntityResponse2
     */
    accountLocator: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityResponse2
     */
    completed: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse2
     */
    locator: string;
    /**
     * 
     * @type {{ [key: string]: EntityResponse2; }}
     * @memberof EntityResponse2
     */
    subEntitiesByLocator: { [key: string]: EntityResponse2; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof EntityResponse2
     */
    values: { [key: string]: Array<string>; };
}


