/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventStreamSubClaimPayableReverseData
 */
export interface EventStreamSubClaimPayableReverseData {
    /**
     * 
     * @type {number}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    amountChange?: number;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    claimLocator: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    policyLocator: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    reserveCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    reserveType?: EventStreamSubClaimPayableReverseDataReserveTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    reversalLocator: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    reversedLocator: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimPayableReverseData
     */
    subClaimLocator: string;
}

/**
    * @export
    * @enum {string}
    */
export enum EventStreamSubClaimPayableReverseDataReserveTypeEnum {
    Loss = 'loss',
    Expense = 'expense'
}



