/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EventResponse } from './event-response';

/**
 * 
 * @export
 * @interface EventPageResponse
 */
export interface EventPageResponse {
    /**
     * 
     * @type {Array<EventResponse>}
     * @memberof EventPageResponse
     */
    events: Array<EventResponse>;
    /**
     * 
     * @type {string}
     * @memberof EventPageResponse
     */
    pagingToken?: string;
}


