/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventStreamSubClaimReserveUpdateData
 */
export interface EventStreamSubClaimReserveUpdateData {
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    claimLocator: string;
    /**
     * 
     * @type {number}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    newAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    oldAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    policyLocator: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    reserveCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    reserveType: EventStreamSubClaimReserveUpdateDataReserveTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EventStreamSubClaimReserveUpdateData
     */
    subClaimLocator: string;
}

/**
    * @export
    * @enum {string}
    */
export enum EventStreamSubClaimReserveUpdateDataReserveTypeEnum {
    Loss = 'loss',
    Expense = 'expense'
}



