/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldConfiguration } from './field-configuration';
import { FrontendExternalDataCallConfiguration } from './frontend-external-data-call-configuration';
import { PerilConfigurationResponse } from './peril-configuration-response';

/**
 * 
 * @export
 * @interface ExposureConfigurationResponse
 */
export interface ExposureConfigurationResponse {
    /**
     * 
     * @type {string}
     * @memberof ExposureConfigurationResponse
     */
    displayName: string;
    /**
     * 
     * @type {Array<FrontendExternalDataCallConfiguration>}
     * @memberof ExposureConfigurationResponse
     */
    externalDataCalls: Array<FrontendExternalDataCallConfiguration>;
    /**
     * 
     * @type {Array<FieldConfiguration>}
     * @memberof ExposureConfigurationResponse
     */
    fields: Array<FieldConfiguration>;
    /**
     * 
     * @type {string}
     * @memberof ExposureConfigurationResponse
     */
    name: string;
    /**
     * 
     * @type {Array<PerilConfigurationResponse>}
     * @memberof ExposureConfigurationResponse
     */
    perils: Array<PerilConfigurationResponse>;
}


