/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldGroupCreateRequest } from './field-group-create-request';
import { PerilCreateRequest } from './peril-create-request';

/**
 * 
 * @export
 * @interface ExposureCreateRequest
 */
export interface ExposureCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ExposureCreateRequest
     */
    exposureName: string;
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof ExposureCreateRequest
     */
    fieldGroups?: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ExposureCreateRequest
     */
    fieldValues?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<PerilCreateRequest>}
     * @memberof ExposureCreateRequest
     */
    perils?: Array<PerilCreateRequest>;
}


