/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExposureCharacteristicsPriceRequest
 */
export interface ExposureCharacteristicsPriceRequest {
    /**
     * 
     * @type {{ [key: string]: { [key: string]: Array<string>; }; }}
     * @memberof ExposureCharacteristicsPriceRequest
     */
    fieldGroupsByLocator: { [key: string]: { [key: string]: Array<string>; }; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ExposureCharacteristicsPriceRequest
     */
    fieldValues?: { [key: string]: Array<string>; };
}


