/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Policy2Response } from './policy2-response';
import { PolicyExposurePerilPricingRequest } from './policy-exposure-peril-pricing-request';

/**
 * 
 * @export
 * @interface ExternalRaterPriceRequest
 */
export interface ExternalRaterPriceRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalRaterPriceRequest
     */
    endorsementLocator?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalRaterPriceRequest
     */
    operation: ExternalRaterPriceRequestOperationEnum;
    /**
     * 
     * @type {Policy2Response}
     * @memberof ExternalRaterPriceRequest
     */
    policy: Policy2Response;
    /**
     * 
     * @type {Array<PolicyExposurePerilPricingRequest>}
     * @memberof ExternalRaterPriceRequest
     */
    policyExposurePerils: Array<PolicyExposurePerilPricingRequest>;
    /**
     * 
     * @type {string}
     * @memberof ExternalRaterPriceRequest
     */
    quoteLocator?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalRaterPriceRequest
     */
    renewalLocator?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ExternalRaterPriceRequestOperationEnum {
    NewBusiness = 'new_business',
    Endorsement = 'endorsement',
    Renewal = 'renewal',
    Reinstatement = 'reinstatement'
}



