/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExternalRaterPricedCharacteristics } from './external-rater-priced-characteristics';

/**
 * 
 * @export
 * @interface ExternalRaterPriceResponse
 */
export interface ExternalRaterPriceResponse {
    /**
     * 
     * @type {string}
     * @memberof ExternalRaterPriceResponse
     */
    exceptionMessage?: string;
    /**
     * 
     * @type {{ [key: string]: ExternalRaterPricedCharacteristics; }}
     * @memberof ExternalRaterPriceResponse
     */
    pricedPerilCharacteristics: { [key: string]: ExternalRaterPricedCharacteristics; };
}


