/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FieldGroupUpdateRequest
 */
export interface FieldGroupUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof FieldGroupUpdateRequest
     */
    fieldGroupLocator: string;
    /**
     * 
     * @type {string}
     * @memberof FieldGroupUpdateRequest
     */
    fieldName: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof FieldGroupUpdateRequest
     */
    fieldValues: { [key: string]: Array<string>; };
}


