/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FinancialTransactionResponse
 */
export interface FinancialTransactionResponse {
    /**
     * 
     * @type {number}
     * @memberof FinancialTransactionResponse
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    amountCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    commissionRecipient?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    feeLocator?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    feeName?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    perilCharacteristicsLocator?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    perilName?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    policyModificationLocator: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    taxLocator?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    taxName?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialTransactionResponse
     */
    type: FinancialTransactionResponseTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FinancialTransactionResponseTypeEnum {
    Premium = 'premium',
    Tax = 'tax',
    Fee = 'fee',
    Commission = 'commission'
}



