/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FinancialTransactionResponse } from './financial-transaction-response';
import { PolicyInvoice2Response } from './policy-invoice2-response';

/**
 * 
 * @export
 * @interface GeneratedInvoiceResponse
 */
export interface GeneratedInvoiceResponse {
    /**
     * 
     * @type {Array<FinancialTransactionResponse>}
     * @memberof GeneratedInvoiceResponse
     */
    financialTransactions: Array<FinancialTransactionResponse>;
    /**
     * 
     * @type {PolicyInvoice2Response}
     * @memberof GeneratedInvoiceResponse
     */
    invoice: PolicyInvoice2Response;
}


