/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommissionResponse } from './commission-response';
import { TaxGroupResponse } from './tax-group-response';

/**
 * 
 * @export
 * @interface GetPerilPriceResponse
 */
export interface GetPerilPriceResponse {
    /**
     * 
     * @type {Array<CommissionResponse>}
     * @memberof GetPerilPriceResponse
     */
    commissions: Array<CommissionResponse>;
    /**
     * 
     * @type {number}
     * @memberof GetPerilPriceResponse
     */
    grossCommissions: number;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    grossCommissionsCurrency: string;
    /**
     * 
     * @type {number}
     * @memberof GetPerilPriceResponse
     */
    grossTaxes: number;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    grossTaxesCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    locator: string;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetPerilPriceResponse
     */
    premium: number;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    premiumCurrency: string;
    /**
     * 
     * @type {Array<TaxGroupResponse>}
     * @memberof GetPerilPriceResponse
     */
    taxes: Array<TaxGroupResponse>;
    /**
     * 
     * @type {number}
     * @memberof GetPerilPriceResponse
     */
    technicalPremium?: number;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    technicalPremiumCurrency: string;
    /**
     * 
     * @type {number}
     * @memberof GetPerilPriceResponse
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof GetPerilPriceResponse
     */
    totalCurrency: string;
}


