/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HealthTestResponse } from './health-test-response';

/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * 
     * @type {number}
     * @memberof HealthResponse
     */
    duration_millis: number;
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    generated_at: string;
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    result: HealthResponseResultEnum;
    /**
     * 
     * @type {{ [key: string]: HealthTestResponse; }}
     * @memberof HealthResponse
     */
    tests: { [key: string]: HealthTestResponse; };
}

/**
    * @export
    * @enum {string}
    */
export enum HealthResponseResultEnum {
    Up = 'up',
    Down = 'down'
}



