/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PolicyDocumentResponse } from './policy-document-response';
import { ReinstatementStatusAndTimeResponse } from './reinstatement-status-and-time-response';

/**
 * 
 * @export
 * @interface LapseReinstatementResponse
 */
export interface LapseReinstatementResponse {
    /**
     * 
     * @type {string}
     * @memberof LapseReinstatementResponse
     */
    currentStatus: LapseReinstatementResponseCurrentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LapseReinstatementResponse
     */
    invoiceLocator?: string;
    /**
     * 
     * @type {string}
     * @memberof LapseReinstatementResponse
     */
    locator: string;
    /**
     * 
     * @type {PolicyDocumentResponse}
     * @memberof LapseReinstatementResponse
     */
    reinstatementDocument?: PolicyDocumentResponse;
    /**
     * 
     * @type {Array<ReinstatementStatusAndTimeResponse>}
     * @memberof LapseReinstatementResponse
     */
    statuses: Array<ReinstatementStatusAndTimeResponse>;
    /**
     * 
     * @type {Array<PolicyDocumentResponse>}
     * @memberof LapseReinstatementResponse
     */
    uploadedDocuments: Array<PolicyDocumentResponse>;
}

/**
    * @export
    * @enum {string}
    */
export enum LapseReinstatementResponseCurrentStatusEnum {
    Open = 'open',
    Closed = 'closed',
    Invoiced = 'invoiced',
    Issued = 'issued'
}



