/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldConfiguration } from './field-configuration';
import { FrontendExternalDataCallConfiguration } from './frontend-external-data-call-configuration';

/**
 * 
 * @export
 * @interface PerilConfigurationResponse
 */
export interface PerilConfigurationResponse {
    /**
     * 
     * @type {number}
     * @memberof PerilConfigurationResponse
     */
    deductible?: number;
    /**
     * 
     * @type {string}
     * @memberof PerilConfigurationResponse
     */
    displayName: string;
    /**
     * 
     * @type {Array<FrontendExternalDataCallConfiguration>}
     * @memberof PerilConfigurationResponse
     */
    externalDataCalls: Array<FrontendExternalDataCallConfiguration>;
    /**
     * 
     * @type {Array<FieldConfiguration>}
     * @memberof PerilConfigurationResponse
     */
    fields: Array<FieldConfiguration>;
    /**
     * 
     * @type {string}
     * @memberof PerilConfigurationResponse
     */
    indemnityInAggregate?: string;
    /**
     * 
     * @type {string}
     * @memberof PerilConfigurationResponse
     */
    indemnityPerEvent?: string;
    /**
     * 
     * @type {string}
     * @memberof PerilConfigurationResponse
     */
    indemnityPerItem?: string;
    /**
     * 
     * @type {number}
     * @memberof PerilConfigurationResponse
     */
    lumpSumPayment?: number;
    /**
     * 
     * @type {string}
     * @memberof PerilConfigurationResponse
     */
    name: string;
}


