/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommissionChangeResponse } from './commission-change-response';
import { TaxChangeResponse } from './tax-change-response';

/**
 * 
 * @export
 * @interface PerilPriceChangeResponse
 */
export interface PerilPriceChangeResponse {
    /**
     * 
     * @type {Array<CommissionChangeResponse>}
     * @memberof PerilPriceChangeResponse
     */
    commissions: Array<CommissionChangeResponse>;
    /**
     * 
     * @type {number}
     * @memberof PerilPriceChangeResponse
     */
    grossCommissionsChange: number;
    /**
     * 
     * @type {number}
     * @memberof PerilPriceChangeResponse
     */
    grossPremiumChange: number;
    /**
     * 
     * @type {number}
     * @memberof PerilPriceChangeResponse
     */
    grossTaxesChange: number;
    /**
     * 
     * @type {string}
     * @memberof PerilPriceChangeResponse
     */
    locator?: string;
    /**
     * 
     * @type {string}
     * @memberof PerilPriceChangeResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PerilPriceChangeResponse
     */
    newGrossCommissions: number;
    /**
     * 
     * @type {number}
     * @memberof PerilPriceChangeResponse
     */
    newGrossPremium: number;
    /**
     * 
     * @type {number}
     * @memberof PerilPriceChangeResponse
     */
    newGrossTaxes: number;
    /**
     * 
     * @type {Array<TaxChangeResponse>}
     * @memberof PerilPriceChangeResponse
     */
    taxes: Array<TaxChangeResponse>;
}


