/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExposureCreateRequest } from './exposure-create-request';
import { FieldGroupCreateRequest } from './field-group-create-request';

/**
 * 
 * @export
 * @interface PolicyCreateRequest4
 */
export interface PolicyCreateRequest4 {
    /**
     * 
     * @type {Array<ExposureCreateRequest>}
     * @memberof PolicyCreateRequest4
     */
    exposures?: Array<ExposureCreateRequest>;
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof PolicyCreateRequest4
     */
    fieldGroups?: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof PolicyCreateRequest4
     */
    fieldValues?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {boolean}
     * @memberof PolicyCreateRequest4
     */
    finalize?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreateRequest4
     */
    paymentScheduleName?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreateRequest4
     */
    policyholderLocator: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreateRequest4
     */
    premiumReportName?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreateRequest4
     */
    productName: string;
}


