/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FinancialTransactionResponse } from './financial-transaction-response';

/**
 * 
 * @export
 * @interface PolicyQuoteInvoiceResponse
 */
export interface PolicyQuoteInvoiceResponse {
    /**
     * 
     * @type {Array<FinancialTransactionResponse>}
     * @memberof PolicyQuoteInvoiceResponse
     */
    financialTransactions: Array<FinancialTransactionResponse>;
}


