/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExposureCreateRequest } from './exposure-create-request';
import { ExposureUpdateRequest } from './exposure-update-request';
import { FieldGroupCreateRequest } from './field-group-create-request';
import { FieldGroupUpdateRequest } from './field-group-update-request';

/**
 * 
 * @export
 * @interface Policy2UpdateRequest
 */
export interface Policy2UpdateRequest {
    /**
     * 
     * @type {Array<ExposureCreateRequest>}
     * @memberof Policy2UpdateRequest
     */
    addExposures: Array<ExposureCreateRequest>;
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof Policy2UpdateRequest
     */
    addFieldGroups: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Policy2UpdateRequest
     */
    fieldValues?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {boolean}
     * @memberof Policy2UpdateRequest
     */
    finalize?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Policy2UpdateRequest
     */
    paymentScheduleName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Policy2UpdateRequest
     */
    removeExposures: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Policy2UpdateRequest
     */
    removeFieldGroups: Array<string>;
    /**
     * 
     * @type {Array<ExposureUpdateRequest>}
     * @memberof Policy2UpdateRequest
     */
    updateExposures: Array<ExposureUpdateRequest>;
    /**
     * 
     * @type {Array<FieldGroupUpdateRequest>}
     * @memberof Policy2UpdateRequest
     */
    updateFieldGroups: Array<FieldGroupUpdateRequest>;
}


