/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PolicyReportRequest
 */
export interface PolicyReportRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PolicyReportRequest
     */
    exposureFields?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PolicyReportRequest
     */
    perilFields?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PolicyReportRequest
     */
    policyFields?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PolicyReportRequest
     */
    productNames?: Array<string>;
}


