/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PolicyInvoicingConfiguration
 */
export interface PolicyInvoicingConfiguration {
    /**
     * 
     * @type {string}
     * @memberof PolicyInvoicingConfiguration
     */
    generatingEvent: PolicyInvoicingConfigurationGeneratingEventEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PolicyInvoicingConfigurationGeneratingEventEnum {
    Quote = 'quote',
    Accept = 'accept',
    Issue = 'issue'
}



