/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CancellationInfo } from './cancellation-info';
import { ExposureResponse } from './exposure-response';
import { FeeResponse } from './fee-response';
import { PolicyCharacteristicsResponse } from './policy-characteristics-response';
import { PolicyDocumentResponse } from './policy-document-response';
import { PolicyInvoice2Response } from './policy-invoice2-response';
import { PolicyModificationResponse } from './policy-modification-response';
import { QuoteSummaryResponse } from './quote-summary-response';

/**
 * 
 * @export
 * @interface Policy2Response
 */
export interface Policy2Response {
    /**
     * 
     * @type {CancellationInfo}
     * @memberof Policy2Response
     */
    cancellation?: CancellationInfo;
    /**
     * 
     * @type {Array<PolicyCharacteristicsResponse>}
     * @memberof Policy2Response
     */
    characteristics: Array<PolicyCharacteristicsResponse>;
    /**
     * 
     * @type {number}
     * @memberof Policy2Response
     */
    configVersion: number;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    displayId: string;
    /**
     * 
     * @type {Array<PolicyDocumentResponse>}
     * @memberof Policy2Response
     */
    documents: Array<PolicyDocumentResponse>;
    /**
     * 
     * @type {Array<ExposureResponse>}
     * @memberof Policy2Response
     */
    exposures: Array<ExposureResponse>;
    /**
     * 
     * @type {Array<FeeResponse>}
     * @memberof Policy2Response
     */
    fees: Array<FeeResponse>;
    /**
     * 
     * @type {number}
     * @memberof Policy2Response
     */
    grossFees: number;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    grossFeesCurrency: string;
    /**
     * 
     * @type {Array<PolicyInvoice2Response>}
     * @memberof Policy2Response
     */
    invoices: Array<PolicyInvoice2Response>;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    locator: string;
    /**
     * 
     * @type {Array<PolicyModificationResponse>}
     * @memberof Policy2Response
     */
    modifications: Array<PolicyModificationResponse>;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    paymentScheduleName?: string;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    policyholderLocator: string;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    premiumReportName?: string;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    productLocator: string;
    /**
     * 
     * @type {string}
     * @memberof Policy2Response
     */
    productName: string;
    /**
     * 
     * @type {QuoteSummaryResponse}
     * @memberof Policy2Response
     */
    quoteSummary?: QuoteSummaryResponse;
}


