/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommissionResponse } from './commission-response';
import { FeeResponse } from './fee-response';
import { FieldErrors } from './field-errors';
import { PremiumReportPremiumResponse } from './premium-report-premium-response';
import { PremiumReportingDocumentResponse } from './premium-reporting-document-response';
import { PremiumReportingInvoiceResponse } from './premium-reporting-invoice-response';
import { TaxGroupResponse } from './tax-group-response';

/**
 * 
 * @export
 * @interface PremiumReportResponse
 */
export interface PremiumReportResponse {
    /**
     * 
     * @type {Array<CommissionResponse>}
     * @memberof PremiumReportResponse
     */
    commissions: Array<CommissionResponse>;
    /**
     * 
     * @type {number}
     * @memberof PremiumReportResponse
     */
    configVersion: number;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportResponse
     */
    displayId: string;
    /**
     * 
     * @type {Array<PremiumReportingDocumentResponse>}
     * @memberof PremiumReportResponse
     */
    documents: Array<PremiumReportingDocumentResponse>;
    /**
     * 
     * @type {Array<FeeResponse>}
     * @memberof PremiumReportResponse
     */
    fees: Array<FeeResponse>;
    /**
     * 
     * @type {FieldErrors}
     * @memberof PremiumReportResponse
     */
    fieldErrors: FieldErrors;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: Array<string>; }; }}
     * @memberof PremiumReportResponse
     */
    fieldGroupsByLocator: { [key: string]: { [key: string]: Array<string>; }; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof PremiumReportResponse
     */
    fieldValues: { [key: string]: Array<string>; };
    /**
     * 
     * @type {number}
     * @memberof PremiumReportResponse
     */
    grossCommissions: number;
    /**
     * 
     * @type {number}
     * @memberof PremiumReportResponse
     */
    grossFees: number;
    /**
     * 
     * @type {number}
     * @memberof PremiumReportResponse
     */
    grossPremium: number;
    /**
     * 
     * @type {number}
     * @memberof PremiumReportResponse
     */
    grossTaxes: number;
    /**
     * 
     * @type {PremiumReportingInvoiceResponse}
     * @memberof PremiumReportResponse
     */
    invoice?: PremiumReportingInvoiceResponse;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportResponse
     */
    locator: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportResponse
     */
    policyLocator: string;
    /**
     * 
     * @type {Array<PremiumReportPremiumResponse>}
     * @memberof PremiumReportResponse
     */
    premiums: Array<PremiumReportPremiumResponse>;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportResponse
     */
    state: PremiumReportResponseStateEnum;
    /**
     * 
     * @type {Array<TaxGroupResponse>}
     * @memberof PremiumReportResponse
     */
    taxGroups: Array<TaxGroupResponse>;
}

/**
    * @export
    * @enum {string}
    */
export enum PremiumReportResponseStateEnum {
    Draft = 'draft',
    Discarded = 'discarded',
    Issued = 'issued',
    Revised = 'revised',
    Reversed = 'reversed'
}



