/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Media } from './media';

/**
 * 
 * @export
 * @interface PremiumReportingPaymentResponse
 */
export interface PremiumReportingPaymentResponse {
    /**
     * 
     * @type {number}
     * @memberof PremiumReportingPaymentResponse
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingPaymentResponse
     */
    amountCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingPaymentResponse
     */
    displayId: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof PremiumReportingPaymentResponse
     */
    fieldValues: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingPaymentResponse
     */
    invoiceLocator: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingPaymentResponse
     */
    locator: string;
    /**
     * 
     * @type {{ [key: string]: Media; }}
     * @memberof PremiumReportingPaymentResponse
     */
    mediaByLocator: { [key: string]: Media; };
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingPaymentResponse
     */
    policyholderLocator: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingPaymentResponse
     */
    tenantLocator: string;
}


