/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PremiumReportPremiumResponse
 */
export interface PremiumReportPremiumResponse {
    /**
     * 
     * @type {string}
     * @memberof PremiumReportPremiumResponse
     */
    category: string;
    /**
     * 
     * @type {number}
     * @memberof PremiumReportPremiumResponse
     */
    premium: number;
}


