/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldConfiguration } from './field-configuration';
import { PolicyDocumentConfiguration } from './policy-document-configuration';

/**
 * 
 * @export
 * @interface PremiumReportingConfigurationResponse
 */
export interface PremiumReportingConfigurationResponse {
    /**
     * 
     * @type {Array<PolicyDocumentConfiguration>}
     * @memberof PremiumReportingConfigurationResponse
     */
    documents: Array<PolicyDocumentConfiguration>;
    /**
     * 
     * @type {Array<FieldConfiguration>}
     * @memberof PremiumReportingConfigurationResponse
     */
    fields: Array<FieldConfiguration>;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingConfigurationResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingConfigurationResponse
     */
    premiumReportingCalculationRevision: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingConfigurationResponse
     */
    productRevisionLocator: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingConfigurationResponse
     */
    reportName: string;
    /**
     * 
     * @type {string}
     * @memberof PremiumReportingConfigurationResponse
     */
    tenantLocator: string;
}


