/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClaimConfigurationResponse } from './claim-configuration-response';
import { PolicyConfigurationResponse } from './policy-configuration-response';
import { PremiumReportingConfigurationResponse } from './premium-reporting-configuration-response';

/**
 * 
 * @export
 * @interface ProductConfiguration2Response
 */
export interface ProductConfiguration2Response {
    /**
     * 
     * @type {ClaimConfigurationResponse}
     * @memberof ProductConfiguration2Response
     */
    claimConfiguration?: ClaimConfigurationResponse;
    /**
     * 
     * @type {number}
     * @memberof ProductConfiguration2Response
     */
    configVersion?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductConfiguration2Response
     */
    name: string;
    /**
     * 
     * @type {PolicyConfigurationResponse}
     * @memberof ProductConfiguration2Response
     */
    policyConfiguration: PolicyConfigurationResponse;
    /**
     * 
     * @type {Array<PremiumReportingConfigurationResponse>}
     * @memberof ProductConfiguration2Response
     */
    premiumReportingConfiguration?: Array<PremiumReportingConfigurationResponse>;
}


