/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LogEvent } from './log-event';

/**
 * 
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
    /**
     * 
     * @type {Array<LogEvent>}
     * @memberof QueryResponse
     */
    logEvents: Array<LogEvent>;
    /**
     * 
     * @type {string}
     * @memberof QueryResponse
     */
    nextPosition: string;
}


