/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuoteSummaryResponseItem
 */
export interface QuoteSummaryResponseItem {
    /**
     * 
     * @type {string}
     * @memberof QuoteSummaryResponseItem
     */
    locator: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteSummaryResponseItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteSummaryResponseItem
     */
    state: QuoteSummaryResponseItemStateEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum QuoteSummaryResponseItemStateEnum {
    Draft = 'draft',
    Quoted = 'quoted',
    Accepted = 'accepted',
    Declined = 'declined',
    Discarded = 'discarded'
}



