/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PolicyDocumentResponse } from './policy-document-response';
import { PolicyPriceChangeResponse } from './policy-price-change-response';

/**
 * 
 * @export
 * @interface ReinstatementResponse
 */
export interface ReinstatementResponse {
    /**
     * The unique identifier to the cancellation that the resinstatement reinstates
     * @type {string}
     * @memberof ReinstatementResponse
     */
    cancellationLocator: string;
    /**
     * 
     * @type {Array<PolicyDocumentResponse>}
     * @memberof ReinstatementResponse
     */
    documents: Array<PolicyDocumentResponse>;
    /**
     * The first invoice generated by the reinstatement accept or issue event
     * @type {string}
     * @memberof ReinstatementResponse
     */
    invoiceLocator?: string;
    /**
     * A unique identifier associated with the reinstatement
     * @type {string}
     * @memberof ReinstatementResponse
     */
    locator: string;
    /**
     * 
     * @type {PolicyPriceChangeResponse}
     * @memberof ReinstatementResponse
     */
    price?: PolicyPriceChangeResponse;
    /**
     * \"The amount the customer needs to pay to reinstate the cancellation. Currently field \"+\"will be the value of the first invoice generated by the reinstatement and will be available on the \"+\"response once the reinstatement is in the accept or issue state.\"
     * @type {number}
     * @memberof ReinstatementResponse
     */
    reinstatementPaymentAmount?: number;
    /**
     * The state of the reinstatement
     * @type {string}
     * @memberof ReinstatementResponse
     */
    state: ReinstatementResponseStateEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ReinstatementResponseStateEnum {
    Draft = 'draft',
    Accepted = 'accepted',
    Issued = 'issued',
    Expired = 'expired'
}



