/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReinstatementStatusAndTimeResponse
 */
export interface ReinstatementStatusAndTimeResponse {
    /**
     * 
     * @type {string}
     * @memberof ReinstatementStatusAndTimeResponse
     */
    status: ReinstatementStatusAndTimeResponseStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ReinstatementStatusAndTimeResponseStatusEnum {
    Open = 'open',
    Closed = 'closed',
    Invoiced = 'invoiced',
    Issued = 'issued'
}



