/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReinstatementAmountDueResponse
 */
export interface ReinstatementAmountDueResponse {
    /**
     * 
     * @type {number}
     * @memberof ReinstatementAmountDueResponse
     */
    grossFeesDue: number;
    /**
     * 
     * @type {number}
     * @memberof ReinstatementAmountDueResponse
     */
    grossPremiumDue: number;
    /**
     * 
     * @type {number}
     * @memberof ReinstatementAmountDueResponse
     */
    grossTaxesDue: number;
    /**
     * 
     * @type {number}
     * @memberof ReinstatementAmountDueResponse
     */
    totalDue: number;
}


