/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReminderConfigurationResponse
 */
export interface ReminderConfigurationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ReminderConfigurationResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReminderConfigurationResponse
     */
    from: ReminderConfigurationResponseFromEnum;
    /**
     * 
     * @type {string}
     * @memberof ReminderConfigurationResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReminderConfigurationResponse
     */
    offset: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ReminderConfigurationResponseFromEnum {
    PolicyEnd = 'policy.end'
}



