/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AutomatedUnderwritingResultResponse } from './automated-underwriting-result-response';
import { ExposureCreateRequest } from './exposure-create-request';
import { FieldGroupCreateRequest } from './field-group-create-request';
import { FieldGroupUpdateRequest } from './field-group-update-request';
import { FutureInvoiceResponse } from './future-invoice-response';
import { PolicyDocumentResponse } from './policy-document-response';
import { PolicyInvoice2Response } from './policy-invoice2-response';
import { PolicyPriceChangeResponse } from './policy-price-change-response';
import { RenewalExposureUpdateRequest } from './renewal-exposure-update-request';

/**
 * 
 * @export
 * @interface RenewalResponse
 */
export interface RenewalResponse {
    /**
     * 
     * @type {Array<ExposureCreateRequest>}
     * @memberof RenewalResponse
     */
    addExposures: Array<ExposureCreateRequest>;
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof RenewalResponse
     */
    addFieldGroups: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {AutomatedUnderwritingResultResponse}
     * @memberof RenewalResponse
     */
    automatedUnderwritingResult?: AutomatedUnderwritingResultResponse;
    /**
     * 
     * @type {Array<PolicyDocumentResponse>}
     * @memberof RenewalResponse
     */
    documents: Array<PolicyDocumentResponse>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RenewalResponse
     */
    endExposures: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RenewalResponse
     */
    fieldValues: { [key: string]: Array<string>; };
    /**
     * 
     * @type {PolicyInvoice2Response}
     * @memberof RenewalResponse
     */
    invoice?: PolicyInvoice2Response;
    /**
     * 
     * @type {string}
     * @memberof RenewalResponse
     */
    locator: string;
    /**
     * 
     * @type {Array<FutureInvoiceResponse>}
     * @memberof RenewalResponse
     */
    plannedInvoices?: Array<FutureInvoiceResponse>;
    /**
     * 
     * @type {string}
     * @memberof RenewalResponse
     */
    policyholderLocator: string;
    /**
     * 
     * @type {string}
     * @memberof RenewalResponse
     */
    policyLocator: string;
    /**
     * 
     * @type {PolicyPriceChangeResponse}
     * @memberof RenewalResponse
     */
    price?: PolicyPriceChangeResponse;
    /**
     * 
     * @type {string}
     * @memberof RenewalResponse
     */
    productLocator: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RenewalResponse
     */
    removeFieldGroups: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RenewalResponse
     */
    state: RenewalResponseStateEnum;
    /**
     * 
     * @type {Array<RenewalExposureUpdateRequest>}
     * @memberof RenewalResponse
     */
    updateExposures: Array<RenewalExposureUpdateRequest>;
    /**
     * 
     * @type {Array<FieldGroupUpdateRequest>}
     * @memberof RenewalResponse
     */
    updateFieldGroups: Array<FieldGroupUpdateRequest>;
}

/**
    * @export
    * @enum {string}
    */
export enum RenewalResponseStateEnum {
    Application = 'application',
    Quoted = 'quoted',
    Accepted = 'accepted',
    Issued = 'issued',
    Invalidated = 'invalidated',
    Discarded = 'discarded'
}



