/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RenewalUpdateRequest } from './renewal-update-request';

/**
 * 
 * @export
 * @interface RenewalActionRequest
 */
export interface RenewalActionRequest {
    /**
     * 
     * @type {string}
     * @memberof RenewalActionRequest
     */
    action?: RenewalActionRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof RenewalActionRequest
     */
    conflictHandling?: RenewalActionRequestConflictHandlingEnum;
    /**
     * 
     * @type {RenewalUpdateRequest}
     * @memberof RenewalActionRequest
     */
    renewalUpdate?: RenewalUpdateRequest;
}

/**
    * @export
    * @enum {string}
    */
export enum RenewalActionRequestActionEnum {
    Discard = 'discard',
    Quote = 'quote',
    Accept = 'accept',
    Issue = 'issue',
    Invalidate = 'invalidate',
    Update = 'update'
}
/**
    * @export
    * @enum {string}
    */
export enum RenewalActionRequestConflictHandlingEnum {
    Block = 'block',
    Invalidate = 'invalidate'
}



