/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReportResponse
 */
export interface ReportResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ReportResponse
     */
    headers: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ReportResponse
     */
    limitReached: boolean;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof ReportResponse
     */
    previewRows: Array<Array<string>>;
    /**
     * 
     * @type {string}
     * @memberof ReportResponse
     */
    resultUrl?: string;
}


