/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SsoQueryLogRequest
 */
export interface SsoQueryLogRequest {
    /**
     * 
     * @type {string}
     * @memberof SsoQueryLogRequest
     */
    hostName: string;
    /**
     * 
     * @type {number}
     * @memberof SsoQueryLogRequest
     */
    limit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SsoQueryLogRequest
     */
    oldestComeFirst?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SsoQueryLogRequest
     */
    position?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoQueryLogRequest
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoQueryLogRequest
     */
    searchPhrase?: string;
}


