/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SsoAccountResponse
 */
export interface SsoAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    accountName: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    accountType: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    accountUuid: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    ontologyUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    tenantName?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    tenantTimezone?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    tenantType?: string;
    /**
     * 
     * @type {string}
     * @memberof SsoAccountResponse
     */
    tenantUuid?: string;
}


