/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LedgerLineItem } from './ledger-line-item';
import { ReserveResponse } from './reserve-response';

/**
 * 
 * @export
 * @interface SubClaimResponse
 */
export interface SubClaimResponse {
    /**
     * 
     * @type {string}
     * @memberof SubClaimResponse
     */
    claimLocator: string;
    /**
     * 
     * @type {string}
     * @memberof SubClaimResponse
     */
    currentStatus: SubClaimResponseCurrentStatusEnum;
    /**
     * 
     * @type {Array<LedgerLineItem>}
     * @memberof SubClaimResponse
     */
    expenseLedger?: Array<LedgerLineItem>;
    /**
     * 
     * @type {ReserveResponse}
     * @memberof SubClaimResponse
     */
    expenseReserve: ReserveResponse;
    /**
     * 
     * @type {string}
     * @memberof SubClaimResponse
     */
    exposureLocator: string;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: Array<string>; }; }}
     * @memberof SubClaimResponse
     */
    fieldGroupsByLocator: { [key: string]: { [key: string]: Array<string>; }; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof SubClaimResponse
     */
    fieldValues: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof SubClaimResponse
     */
    locator: string;
    /**
     * 
     * @type {Array<LedgerLineItem>}
     * @memberof SubClaimResponse
     */
    lossLedger?: Array<LedgerLineItem>;
    /**
     * 
     * @type {ReserveResponse}
     * @memberof SubClaimResponse
     */
    lossReserve: ReserveResponse;
    /**
     * 
     * @type {string}
     * @memberof SubClaimResponse
     */
    perilLocator: string;
    /**
     * 
     * @type {string}
     * @memberof SubClaimResponse
     */
    reserveCurrency: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SubClaimResponseCurrentStatusEnum {
    Open = 'open',
    Closed = 'closed'
}



