/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubClaimPayableCreateRequest
 */
export interface SubClaimPayableCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof SubClaimPayableCreateRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof SubClaimPayableCreateRequest
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof SubClaimPayableCreateRequest
     */
    recipient?: string;
    /**
     * 
     * @type {string}
     * @memberof SubClaimPayableCreateRequest
     */
    reserveType: SubClaimPayableCreateRequestReserveTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubClaimPayableCreateRequest
     */
    subClaimLocator: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SubClaimPayableCreateRequestReserveTypeEnum {
    Loss = 'loss',
    Expense = 'expense'
}



