/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldGroupCreateRequest } from './field-group-create-request';
import { FieldGroupUpdateRequest } from './field-group-update-request';
import { ReserveSetRequest } from './reserve-set-request';

/**
 * 
 * @export
 * @interface SubClaimUpdateRequest
 */
export interface SubClaimUpdateRequest {
    /**
     * 
     * @type {Array<FieldGroupCreateRequest>}
     * @memberof SubClaimUpdateRequest
     */
    addFieldGroups: Array<FieldGroupCreateRequest>;
    /**
     * 
     * @type {ReserveSetRequest}
     * @memberof SubClaimUpdateRequest
     */
    expenseReserve?: ReserveSetRequest;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof SubClaimUpdateRequest
     */
    fieldValues?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof SubClaimUpdateRequest
     */
    locator: string;
    /**
     * 
     * @type {ReserveSetRequest}
     * @memberof SubClaimUpdateRequest
     */
    lossReserve?: ReserveSetRequest;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubClaimUpdateRequest
     */
    removeFieldGroups: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SubClaimUpdateRequest
     */
    status?: SubClaimUpdateRequestStatusEnum;
    /**
     * 
     * @type {Array<FieldGroupUpdateRequest>}
     * @memberof SubClaimUpdateRequest
     */
    updateFieldGroups: Array<FieldGroupUpdateRequest>;
}

/**
    * @export
    * @enum {string}
    */
export enum SubClaimUpdateRequestStatusEnum {
    Open = 'open',
    Closed = 'closed'
}



