/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubEntityCreateRequest
 */
export interface SubEntityCreateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof SubEntityCreateRequest
     */
    completed: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubEntityCreateRequest
     */
    localId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubEntityCreateRequest
     */
    ontologyUri: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof SubEntityCreateRequest
     */
    values: { [key: string]: Array<string>; };
}


