/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubClaimSummary
 */
export interface SubClaimSummary {
    /**
     * 
     * @type {number}
     * @memberof SubClaimSummary
     */
    expensePayableAmount: number;
    /**
     * 
     * @type {number}
     * @memberof SubClaimSummary
     */
    expenseReserveAmount: number;
    /**
     * 
     * @type {number}
     * @memberof SubClaimSummary
     */
    lossPayableAmount: number;
    /**
     * 
     * @type {number}
     * @memberof SubClaimSummary
     */
    lossReserveAmount: number;
    /**
     * 
     * @type {string}
     * @memberof SubClaimSummary
     */
    reserveCurrency: string;
}


