/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CalculationResponse } from '../model';
// @ts-ignore
import { CheckExistingPerilPremiumRequest } from '../model';
// @ts-ignore
import { CheckPerilPremiumRequest } from '../model';
/**
 * CalculationApi - axios parameter creator
 * @export
 */
export const CalculationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary checkExistingPerilPremiumUsingPOST
         * @param {CheckExistingPerilPremiumRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkExistingPerilPremiumUsingPOST: async (request: CheckExistingPerilPremiumRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('checkExistingPerilPremiumUsingPOST', 'request', request)
            const localVarPath = `/calculation/checkExistingPerilPremium`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary checkPerilPremiumUsingPOST
         * @param {CheckPerilPremiumRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPerilPremiumUsingPOST: async (request: CheckPerilPremiumRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('checkPerilPremiumUsingPOST', 'request', request)
            const localVarPath = `/calculation/checkPerilPremium`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CalculationApi - functional programming interface
 * @export
 */
export const CalculationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CalculationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary checkExistingPerilPremiumUsingPOST
         * @param {CheckExistingPerilPremiumRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkExistingPerilPremiumUsingPOST(request: CheckExistingPerilPremiumRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalculationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkExistingPerilPremiumUsingPOST(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary checkPerilPremiumUsingPOST
         * @param {CheckPerilPremiumRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkPerilPremiumUsingPOST(request: CheckPerilPremiumRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalculationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkPerilPremiumUsingPOST(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CalculationApi - factory interface
 * @export
 */
export const CalculationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CalculationApiFp(configuration)
    return {
        /**
         * 
         * @summary checkExistingPerilPremiumUsingPOST
         * @param {CheckExistingPerilPremiumRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkExistingPerilPremiumUsingPOST(request: CheckExistingPerilPremiumRequest, options?: any): AxiosPromise<CalculationResponse> {
            return localVarFp.checkExistingPerilPremiumUsingPOST(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary checkPerilPremiumUsingPOST
         * @param {CheckPerilPremiumRequest} request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPerilPremiumUsingPOST(request: CheckPerilPremiumRequest, options?: any): AxiosPromise<CalculationResponse> {
            return localVarFp.checkPerilPremiumUsingPOST(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CalculationApi - object-oriented interface
 * @export
 * @class CalculationApi
 * @extends {BaseAPI}
 */
export class CalculationApi extends BaseAPI {
    /**
     * 
     * @summary checkExistingPerilPremiumUsingPOST
     * @param {CheckExistingPerilPremiumRequest} request 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalculationApi
     */
    public checkExistingPerilPremiumUsingPOST(request: CheckExistingPerilPremiumRequest, options?: any) {
        return CalculationApiFp(this.configuration).checkExistingPerilPremiumUsingPOST(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary checkPerilPremiumUsingPOST
     * @param {CheckPerilPremiumRequest} request 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalculationApi
     */
    public checkPerilPremiumUsingPOST(request: CheckPerilPremiumRequest, options?: any) {
        return CalculationApiFp(this.configuration).checkPerilPremiumUsingPOST(request, options).then((request) => request(this.axios, this.basePath));
    }
}
