/* tslint:disable */
/* eslint-disable */
/**
 * Socotra API Reference
 * Socotra REST API Description
 *
 * The version of the OpenAPI document: 1.3.191
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PremiumReportResponse } from '../model';
// @ts-ignore
import { PremiumReportUpdateRequest } from '../model';
/**
 * PremiumReportApi - axios parameter creator
 * @export
 */
export const PremiumReportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary discardPremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discardPremiumReportUsingPATCH: async (premiumReportLocator: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'premiumReportLocator' is not null or undefined
            assertParamExists('discardPremiumReportUsingPATCH', 'premiumReportLocator', premiumReportLocator)
            const localVarPath = `/premiumReports/{premiumReportLocator}/discard`
                .replace(`{${"premiumReportLocator"}}`, encodeURIComponent(String(premiumReportLocator)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getPremiumReportUsingGET
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPremiumReportUsingGET: async (premiumReportLocator: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'premiumReportLocator' is not null or undefined
            assertParamExists('getPremiumReportUsingGET', 'premiumReportLocator', premiumReportLocator)
            const localVarPath = `/premiumReports/{premiumReportLocator}`
                .replace(`{${"premiumReportLocator"}}`, encodeURIComponent(String(premiumReportLocator)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary issuePremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        issuePremiumReportUsingPATCH: async (premiumReportLocator: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'premiumReportLocator' is not null or undefined
            assertParamExists('issuePremiumReportUsingPATCH', 'premiumReportLocator', premiumReportLocator)
            const localVarPath = `/premiumReports/{premiumReportLocator}/issue`
                .replace(`{${"premiumReportLocator"}}`, encodeURIComponent(String(premiumReportLocator)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary updatePremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {PremiumReportUpdateRequest} updateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePremiumReportUsingPATCH: async (premiumReportLocator: string, updateRequest: PremiumReportUpdateRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'premiumReportLocator' is not null or undefined
            assertParamExists('updatePremiumReportUsingPATCH', 'premiumReportLocator', premiumReportLocator)
            // verify required parameter 'updateRequest' is not null or undefined
            assertParamExists('updatePremiumReportUsingPATCH', 'updateRequest', updateRequest)
            const localVarPath = `/premiumReports/{premiumReportLocator}`
                .replace(`{${"premiumReportLocator"}}`, encodeURIComponent(String(premiumReportLocator)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PremiumReportApi - functional programming interface
 * @export
 */
export const PremiumReportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PremiumReportApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary discardPremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discardPremiumReportUsingPATCH(premiumReportLocator: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discardPremiumReportUsingPATCH(premiumReportLocator, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary getPremiumReportUsingGET
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPremiumReportUsingGET(premiumReportLocator: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PremiumReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPremiumReportUsingGET(premiumReportLocator, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary issuePremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async issuePremiumReportUsingPATCH(premiumReportLocator: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PremiumReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.issuePremiumReportUsingPATCH(premiumReportLocator, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary updatePremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {PremiumReportUpdateRequest} updateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePremiumReportUsingPATCH(premiumReportLocator: string, updateRequest: PremiumReportUpdateRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PremiumReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePremiumReportUsingPATCH(premiumReportLocator, updateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PremiumReportApi - factory interface
 * @export
 */
export const PremiumReportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PremiumReportApiFp(configuration)
    return {
        /**
         * 
         * @summary discardPremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discardPremiumReportUsingPATCH(premiumReportLocator: string, options?: any): AxiosPromise<void> {
            return localVarFp.discardPremiumReportUsingPATCH(premiumReportLocator, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getPremiumReportUsingGET
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPremiumReportUsingGET(premiumReportLocator: string, options?: any): AxiosPromise<PremiumReportResponse> {
            return localVarFp.getPremiumReportUsingGET(premiumReportLocator, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary issuePremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        issuePremiumReportUsingPATCH(premiumReportLocator: string, options?: any): AxiosPromise<PremiumReportResponse> {
            return localVarFp.issuePremiumReportUsingPATCH(premiumReportLocator, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary updatePremiumReportUsingPATCH
         * @param {string} premiumReportLocator 
         * @param {PremiumReportUpdateRequest} updateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePremiumReportUsingPATCH(premiumReportLocator: string, updateRequest: PremiumReportUpdateRequest, options?: any): AxiosPromise<PremiumReportResponse> {
            return localVarFp.updatePremiumReportUsingPATCH(premiumReportLocator, updateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PremiumReportApi - object-oriented interface
 * @export
 * @class PremiumReportApi
 * @extends {BaseAPI}
 */
export class PremiumReportApi extends BaseAPI {
    /**
     * 
     * @summary discardPremiumReportUsingPATCH
     * @param {string} premiumReportLocator 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PremiumReportApi
     */
    public discardPremiumReportUsingPATCH(premiumReportLocator: string, options?: any) {
        return PremiumReportApiFp(this.configuration).discardPremiumReportUsingPATCH(premiumReportLocator, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getPremiumReportUsingGET
     * @param {string} premiumReportLocator 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PremiumReportApi
     */
    public getPremiumReportUsingGET(premiumReportLocator: string, options?: any) {
        return PremiumReportApiFp(this.configuration).getPremiumReportUsingGET(premiumReportLocator, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary issuePremiumReportUsingPATCH
     * @param {string} premiumReportLocator 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PremiumReportApi
     */
    public issuePremiumReportUsingPATCH(premiumReportLocator: string, options?: any) {
        return PremiumReportApiFp(this.configuration).issuePremiumReportUsingPATCH(premiumReportLocator, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary updatePremiumReportUsingPATCH
     * @param {string} premiumReportLocator 
     * @param {PremiumReportUpdateRequest} updateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PremiumReportApi
     */
    public updatePremiumReportUsingPATCH(premiumReportLocator: string, updateRequest: PremiumReportUpdateRequest, options?: any) {
        return PremiumReportApiFp(this.configuration).updatePremiumReportUsingPATCH(premiumReportLocator, updateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
